"""add index to short_code

Revision ID: e7feb4ae66d9
Revises: f564df42fb54
Create Date: 2026-08-04 18:32:34.517346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7feb4ae66d9'
down_revision: Union[str, Sequence[str], None] = 'f564df42fb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_short_code_key'), 'urls', type_='unique')
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.create_unique_constraint(op.f('urls_short_code_key'), 'urls', ['short_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
